<?php

    // this will add to the cats table generated by ex10-7.php

    require_once '../login.php';
    $conn = new mysqli($hn, $un, $pw, $db);
    if ($conn->connect_error) die($conn->connect_error);

    $query = "insert into cats values(null, 'Cheetah', 'Charly', 3)";
    $result = $conn->query($query);
    if (!$result) die("Database access failed: " . $conn->error);
