<?php

    // will drop cats table generated by ex10-7.php

    require_once '../login.php';
    $conn = new mysqli($hn, $un, $pw, $db);
    if ($conn->connect_error) die($conn->connect_error);

    $query = "drop table cats";
    $result = $conn->query($query);
    if (!$result) die ("Database access failed: " . $conn->error);
